- name: install httpd packages
  yum: 
       name: "{{ web }}"
       state: installed 
      
- name: start services
  service: 
       name: "{{ web }}"
       state: started
       enabled: true


- name: import apache file
  import_tasks: task1.yml

